### Route Collections
GET http://64ed31429cbded49acab4281.cloud.lan/Apothéose/collexion/projet-12-collexion-back/public/api/collection/2 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MDc5MjMwOTIsImV4cCI6MTcwNzkyNjY5Miwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQGFkbWluLmNvbSJ9.wmynBNEOLSLErih6uFqQHdsPoh9lU2lJ6VWPIaWjYWrjVtPaOcRKju6ih5FJoxOMmbGe_tKPHbgMS8yVHC1awr8u8JBgnsFXrH86eFNr3KgUeqQPH9VKIBuPsFoc7Stsy3y3jZflLDElN51F1PesRYUK59yWfmayGBDyqUrky7nOR3746ry9zan2PQVRI35_7d9ANHTNQXHhbtTJ5OXMUlXuF3orstTe3Thf0KwpyuDtHeA-lt1gKVT_UEkRQr2ujonEj-ZkarKd7S4HhAWEWMh3bw86kxT2DiPFmK-fKRoIEAfkWnlc_bPsGuJ_SDdTH9gHrz2ri7afR9JuqESgQg


### Route Login
POST http://64ed31429cbded49acab4281.cloud.lan/Apothéose/collexion/projet-12-collexion-back/public/api/login_check HTTP/1.1
content-type: application/json

{
  "username": "admin@admin.com",
  "password": "admin"
}

### Route Get User
GET http://64ed31429cbded49acab4281.cloud.lan/Apothéose/collexion/projet-12-collexion-back/public/api/users HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MDc5MjMwOTIsImV4cCI6MTcwNzkyNjY5Miwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQGFkbWluLmNvbSJ9.wmynBNEOLSLErih6uFqQHdsPoh9lU2lJ6VWPIaWjYWrjVtPaOcRKju6ih5FJoxOMmbGe_tKPHbgMS8yVHC1awr8u8JBgnsFXrH86eFNr3KgUeqQPH9VKIBuPsFoc7Stsy3y3jZflLDElN51F1PesRYUK59yWfmayGBDyqUrky7nOR3746ry9zan2PQVRI35_7d9ANHTNQXHhbtTJ5OXMUlXuF3orstTe3Thf0KwpyuDtHeA-lt1gKVT_UEkRQr2ujonEj-ZkarKd7S4HhAWEWMh3bw86kxT2DiPFmK-fKRoIEAfkWnlc_bPsGuJ_SDdTH9gHrz2ri7afR9JuqESgQg

### Route Delete Collection
DELETE http://64ed31429cbded49acab4281.cloud.lan/Apothéose/collexion/projet-12-collexion-back/public/api//api/collection/2 HTTP/1.1






