### Route Collections
GET http://64ed31429cbded49acab4281.cloud.lan/Apothéose/collexion/projet-12-collexion-back/public/api/collections HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MDc4OTk1MTAsImV4cCI6MTcwNzkwMzExMCwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQGFkbWluLmNvbSJ9.Jwx0eDCSQQteMgBf8O8g4gkZRHndc6MK-zq8JA5nImd8K08tjCb3DaWTqVgrIhuRl02bxxFhUsFAl_C-mUCE0kH_eehOHkqyC6WQscsv3R_IAE_3iPTXV5b0bxYPl7Q0I2rLghH9Jipc9WreMhwN-0oLuE7RPnrEIozOGQ5hmctX3mE46gWh9qFxbr4e8rCRc_97YaELd7bb7knkfyrS2cq7adBQVRwBwvWtfQgRWpiQo6NIca0Hi8WUJWkGUItDbiDGpLDNPzNNxQbqIjJKGAOZ6ZdHeLjNYPag14L6trMU6OTaPgxCnX-Koh-GkFA-CTO0oulsI6T7mFFbs6p8iA


### Route Login
POST http://64ed31429cbded49acab4281.cloud.lan/Apothéose/collexion/projet-12-collexion-back/public/api/login_check HTTP/1.1
content-type: application/json

{
  "username": "admin@admin.com",
  "password": "admin"
}

### Route Delete Collection
DELETE http://64ed31429cbded49acab4281.cloud.lan/Apothéose/collexion/projet-12-collexion-back/public/api//api/collection/2 HTTP/1.1






