### Route Collections
GET http://ec2-16-170-215-204.eu-north-1.compute.amazonaws.com/index.php/api/collections HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MDgwMDU4OTgsImV4cCI6MTcwODAwOTQ5OCwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQGFkbWluLmNvbSJ9.uxNvhdjUxuLkWDIEWN2IDAolQAiEuos2PioahqhbLDEaBqR9c-TJW4Ol0eN-jzCc87-Y6xcdflDd1STbpqbJQucTykx-Jw9hLp2BPTxR-bgEl1osTzv4FyrjH5x_FsRyBjq9HEmQeJmeVd6V1jKnGfi1FI824VZbD5rRhGj-13k4Z6LTy-5P_AKbpKydQvAjJVxIm6Lon4UUV7qM-WQ0htGkWI15DFyZyyqV8r4kePnG5aK66wVeOPjkHVheuRTvJ5sbGc0gHH0xP4DufZMOfEPaKxLsi-qYb-hGDV8rRJU2t77r-f-jlVXnpC7Sgxth9IO_be-lQIZ2eKOPPcfUBw

### Route GET Collection
GET http://ec2-16-170-215-204.eu-north-1.compute.amazonaws.com/index.php/api/collection/2 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MDgwMDU4OTgsImV4cCI6MTcwODAwOTQ5OCwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQGFkbWluLmNvbSJ9.uxNvhdjUxuLkWDIEWN2IDAolQAiEuos2PioahqhbLDEaBqR9c-TJW4Ol0eN-jzCc87-Y6xcdflDd1STbpqbJQucTykx-Jw9hLp2BPTxR-bgEl1osTzv4FyrjH5x_FsRyBjq9HEmQeJmeVd6V1jKnGfi1FI824VZbD5rRhGj-13k4Z6LTy-5P_AKbpKydQvAjJVxIm6Lon4UUV7qM-WQ0htGkWI15DFyZyyqV8r4kePnG5aK66wVeOPjkHVheuRTvJ5sbGc0gHH0xP4DufZMOfEPaKxLsi-qYb-hGDV8rRJU2t77r-f-jlVXnpC7Sgxth9IO_be-lQIZ2eKOPPcfUBw

### Route POST Collection
POST http://ec2-16-170-215-204.eu-north-1.compute.amazonaws.com/index.php/api/collection/create HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MDgwMTIzMDAsImV4cCI6MTcwODAxNTkwMCwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQGFkbWluLmNvbSJ9.fw18HfQWQfNj2kJ8lMeMJ9xHpxkRgGZHclI-x0J7JOShsNUJZpyUmSPFuK0eAbiiC1E8apha4kGcpRc7X5GT8s7Vc6Hhy0EKf2ov2opnOdCXCWKIPzyyrbRHqxIMthoyIwPpE6wzSqlsjUmqZ-4hFIJ0Eds6SmFeBv5E1ZIzJkts8ZIVfPkEzsNVcHY87vWyFwjzXx9ntb96VKVVdhckeYEtYGXAKKvCqGHEmAjDPAEIMRjNLU9JPuCdjSQdYoMA69GATagY1OyADbSPaGl-3Q3LA88PmzqjM0RzaH6NO-WzXWHnpgEhzovJwaTPc3f_aafhu6YXEbNpPE3o2583pQ

{
  "name": "nouvelle collection test",
  "description": "ceci est un test, attention",
  "image": "https://picsum.photos/1000"
}


### Route Login
POST http://ec2-16-170-215-204.eu-north-1.compute.amazonaws.com/index.php/api/login_check HTTP/1.1
content-type: application/json

{
  "username": "admin@admin.com",
  "password": "admin"
}

### Route Get User
GET http://ec2-16-170-215-204.eu-north-1.compute.amazonaws.com/index.php/api/users HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MDgwMDU4OTgsImV4cCI6MTcwODAwOTQ5OCwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQGFkbWluLmNvbSJ9.uxNvhdjUxuLkWDIEWN2IDAolQAiEuos2PioahqhbLDEaBqR9c-TJW4Ol0eN-jzCc87-Y6xcdflDd1STbpqbJQucTykx-Jw9hLp2BPTxR-bgEl1osTzv4FyrjH5x_FsRyBjq9HEmQeJmeVd6V1jKnGfi1FI824VZbD5rRhGj-13k4Z6LTy-5P_AKbpKydQvAjJVxIm6Lon4UUV7qM-WQ0htGkWI15DFyZyyqV8r4kePnG5aK66wVeOPjkHVheuRTvJ5sbGc0gHH0xP4DufZMOfEPaKxLsi-qYb-hGDV8rRJU2t77r-f-jlVXnpC7Sgxth9IO_be-lQIZ2eKOPPcfUBw

### Route Delete Collection
DELETE http://ec2-16-170-215-204.eu-north-1.compute.amazonaws.com/index.php/api/collection/delete/2 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MDgwMDU4OTgsImV4cCI6MTcwODAwOTQ5OCwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQGFkbWluLmNvbSJ9.uxNvhdjUxuLkWDIEWN2IDAolQAiEuos2PioahqhbLDEaBqR9c-TJW4Ol0eN-jzCc87-Y6xcdflDd1STbpqbJQucTykx-Jw9hLp2BPTxR-bgEl1osTzv4FyrjH5x_FsRyBjq9HEmQeJmeVd6V1jKnGfi1FI824VZbD5rRhGj-13k4Z6LTy-5P_AKbpKydQvAjJVxIm6Lon4UUV7qM-WQ0htGkWI15DFyZyyqV8r4kePnG5aK66wVeOPjkHVheuRTvJ5sbGc0gHH0xP4DufZMOfEPaKxLsi-qYb-hGDV8rRJU2t77r-f-jlVXnpC7Sgxth9IO_be-lQIZ2eKOPPcfUBw






